apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-notification-db
  namespace: fiap
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: notification-db
