apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-image-upload-db
  namespace: fiap
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: image-upload-db
