apiVersion: v1
kind: Pod
metadata:
  name: db-image-upload
  namespace: fiap
  labels:
    app: db-image-upload
spec:
  containers:
    - name: db-image-upload-container
      image: "postgres:14"
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: db-configmap-image-upload
        - secretRef:
            name: db-secret
      volumeMounts:
        - name: image-upload-db-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres-data
  volumes:
    - name: image-upload-db-data
      persistentVolumeClaim:
        claimName: pvc-image-upload-db
