apiVersion: v1
kind: Pod
metadata:
  name: db-image-upload
  namespace: fiap
  labels:
    app: db-image-upload
spec:
  containers:
    - name: db-image-upload-container
      image: "postgres:14"
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: db-configmap-image-upload
        - secretRef:
            name: db-secret
