apiVersion: v1
kind: Pod
metadata:
  name: db-notification
  namespace: fiap
  labels:
    app: db-notification
spec:
  containers:
    - name: db-notification-container
      image: "postgres:14"
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: db-configmap-notification
        - secretRef:
            name: db-secret
