apiVersion: v1
kind: Pod
metadata:
  name: db-video-processing
  namespace: fiap
  labels:
    app: db-video-processing
spec:
  containers:
    - name: db-video-processing-container
      image: "postgres:14"
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: db-configmap-video-processing
        - secretRef:
            name: db-secret
