apiVersion: v1
kind: Service
metadata:
  name: svc-video-processing-api
  namespace: fiap
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 3000
  selector:
    app: video-processing-api