apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-api-deployment
  namespace: fiap
spec:
  selector:
    matchLabels:
      app: notification-api
  template:
    metadata:
      labels:
        app: notification-api
    spec:
      containers:
        - name: notification-api-container
          image: gabrielumbelino/fiap-hackathon-notification-service:latest
          ports:
            - name: http
              containerPort: 8081
          envFrom:
            - configMapRef:
                name: notification-api-configmap
            - secretRef:
                name: db-secret
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 100m